HelperWv: Fix TranslateWraper
peak3d/inputstream.adaptive pull request #1691
Opened 2024-10-11 20:50 UTC by knaerzche

As noted in the comment above this method, the seperator is '+', not ','. Fix it.

## Description
`TranslateWrapper` in `src/decrypters/HelperWv.cpp`uses a wrong separator for splitting the wrapper methods. Pretty obvious fix

## Motivation and context
Fix a bug.

## How has this been tested?
With a stream using `json+base64` (`JB`)

## Screenshots (if appropriate):

## Types of change

- [ x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

2024-10-12 06:51 UTC, CastagnaIT requested changes
this change is wrong,
as is also explained on wiki, the code its correct
i just forgot to fix the above method comment

2024-10-12 08:40 UTC, knaerzche commented
It's not like I scanned the comments in this code and adapted the code to the comment: Playing a stream with the mentioned "unwrapping method" fails with: `Cannot translate license wrapper, unknown type json+base64` and this changes fixes it. I didn't look too deep in this code, but I'd guess it comes from here: https://github.com/xbmc/inputstream.adaptive/blob/8720557ed939ba5d4f5e227b052e3daad9e2f3e3/src/CompKodiProps.cpp#L520 - it uses `+` as seperator, not `.`

2024-10-12 09:06 UTC, CastagnaIT commented
yeah good catch
please fix all them, and also the above method comment

2024-10-12 14:12 UTC, knaerzche commented
Done. (Took some time for me to find the wiki entry you were referring to)

2024-10-13 08:00 UTC, CastagnaIT approved these changes
well done
thank you for your first contrib

2024-10-13 08:01 UTC, merged