Check KEYFORMAT before METHOD
peak3d/inputstream.adaptive pull request #421
Opened 2020-04-15 04:43 UTC by matthuisman

Some providers (Apple+) use METHOD=SAMPLE-AES instead of correct METHOD=SAMPLE-AES-CTR
This change makes IA check the KEYFORMAT first.
SAMPLE-AES-CTR check no longer required as Widevine already returned after the KEYFORMAT check.

2020-04-15 06:04 UTC, matthuisman commented
`#EXT-X-KEY:URI="data:text/plain;base64,AAAAOHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABgSEAAAAAAD5ndGYzEgICAgICBI88aJmwY=",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1",METHOD=SAMPLE-AES` should be parsed as Widevine

2020-04-15 06:20 UTC, matthuisman commented
actually, this needs work

The parser fails as the first line has METHOD=SAMPLE-AES in it but no urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
The parser needs to check all lines before failing.

Even if the above was correct and had METHOD=SAMPLE-AES-CTR - it would still fail as the first line has SAMPLE-AES

2020-04-17 20:45 UTC, peak3d commented
@matthuisman sorry, there has now much changed in hlskid, so you'll have to provide a new PR

2020-04-17 20:48 UTC, matthuisman commented
Should I base new PR on master?

On Sat, 18 Apr 2020, 8:45 AM Markus Pfau, <notifications@github.com> wrote:

> @matthuisman <https://github.com/matthuisman> sorry, there has now much
> changed in hlskid, so you'll have to provide a new PR
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/peak3d/inputstream.adaptive/pull/421#issuecomment-615455658>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABPQAKN6TGH5ELSBIWEHDR3RNC5WDANCNFSM4MIIL7AA>
> .
>

2020-04-17 20:48 UTC, matthuisman commented
Should I base new PR on master?

2020-04-17 20:49 UTC, peak3d requested changes
It's too hard for me too read, this PR should be splitted into 2, one for changes, and one for cosmetic.
Beside this 15 commits are not what we want to see in git history, pls. suqsh all your commits into one as long there are no reasons why to use separate commits

2020-04-17 20:49 UTC, peak3d commented on src/parser/HLSTree.cpp
> -  Log(LOGLEVEL_WARNING, "Unsupported encryption method: %s with keyformat %s", map["METHOD"].c_str(), map["KEYFORMAT"].c_str());
should remain WARNING

2020-04-17 20:49 UTC, peak3d commented on src/parser/HLSTree.h
> -      ENCRYPTIONTYPE_INVALID = 0,
cosmetic? It's INVALID for use in inputstream.adaptive

2020-04-17 20:54 UTC, matthuisman commented on src/parser/HLSTree.h
> -      ENCRYPTIONTYPE_INVALID = 0,
i went for ENCRYPTIONTYPE_UNSUPPORTED (to cover UNKNOWN and invalid)
as with the new behavour, we are not actually checking for unspported.
Only checking for supported.
So any thing else would either be unknown or invalid - therefore UNSUPPORTED
It also matches the log message better

2020-04-17 20:55 UTC, matthuisman commented
ill close this pull request and do a nicer one based on lastest commit in hlksid branch

2020-04-17 20:55 UTC, closed without merging