Support subtitle colors in span tags
peak3d/inputstream.adaptive pull request #442
Opened 2020-05-10 17:27 UTC by mediaminister

This fixes https://github.com/peak3d/inputstream.adaptive/issues/386

2020-05-15 18:45 UTC, peak3d requested changes

2020-05-15 18:45 UTC, peak3d commented on src/parser/TTML.cpp
> +              else if (strcmp((const char*)*attr, "color") == 0) {
Pls. brackets on new line, or run git clang-format after `git add` (but before `git commit`).

2020-05-15 20:29 UTC, mediaminister commented on src/parser/TTML.cpp
> +              else if (strcmp((const char*)*attr, "color") == 0) {
Done.

2020-05-16 20:42 UTC, peak3d approved these changes

2020-05-16 20:43 UTC, merged