[HLS] Update base_domain when an effective_url (i.e. redirect) is being used.
peak3d/inputstream.adaptive pull request #490
Opened 2020-07-23 20:48 UTC by smf007

Fixes HLS problems of Issue #473

When a redirect is used, the base_domain should be updated to reflect the domain of the effective URL.

2020-07-24 02:44 UTC, matthuisman commented
I have gone ahead and done the cleanup that will make this PR obsolete:
https://github.com/peak3d/inputstream.adaptive/pull/492

2020-10-15 18:22 UTC, peak3d requested changes
This change is against the concept, please add soething like this:

https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/parser/HLSTree.cpp#L430

at this place:

https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/parser/HLSTree.cpp#L167

and tell me if this solves the issue. If not, pls. provide a kodi log.

2020-10-15 19:10 UTC, peak3d commented
https://github.com/peak3d/inputstream.adaptive/issues/531

2020-10-16 18:56 UTC, peak3d commented
sould be fixed by this: 8bea82b3c323ef30b30806724304ce91aa86d7ae

2020-10-16 18:56 UTC, closed without merging