[DASH] Fix MPD redirects.  Issue #473
peak3d/inputstream.adaptive pull request #491
Opened 2020-07-23 21:56 UTC by smf007

Fixes issue #473.  To fix redirects, apply the effective URL to the download URL, then delete the effective URL.

2020-07-23 23:10 UTC, matthuisman commented
the above lines could also be changed

from
`  std::string download_url = manifest_url_;
  if (!effective_url_.empty() && download_url.find(base_url_) == 0)	  if (!effective_url_.empty() && download_url.find(base_url_) == 0)
    download_url.replace(0, base_url_.size(), effective_url_);	    download_url.replace(0, base_url_.size(), effective_url_);

  bool ret = download(download_url.c_str(), manifest_headers_) && !periods_.empty();	  bool ret = download(download_url.c_str(), manifest_headers_) && !periods_.empty();
`
to
`bool ret = download(manifest_url_.c_str(), manifest_headers_) && !periods_.empty();	  bool ret = download(download_url.c_str(), manifest_headers_) && !periods_.empty();`

2020-07-24 02:44 UTC, matthuisman commented
I have gone ahead and done the cleanup that will make this PR obsolete:
https://github.com/peak3d/inputstream.adaptive/pull/492

2020-10-15 18:25 UTC, peak3d requested changes
Is there any reason, why this is not working?
https://github.com/peak3d/inputstream.adaptive/pull/491/files#diff-f5e439696055d30c282716f0d0fc54ee6612edb6e4f29ef91b4c3a00cd426679L1554-L1556

2020-10-15 19:10 UTC, peak3d commented
https://github.com/peak3d/inputstream.adaptive/issues/531

2020-10-16 18:57 UTC, peak3d commented
I'll backport 8bea82b3c323ef30b30806724304ce91aa86d7ae

2020-10-16 18:57 UTC, closed without merging