Support fpsScale in AdaptationSets
peak3d/inputstream.adaptive pull request #575
Opened 2020-12-16 21:21 UTC by matthuisman

Below MPD uses frameRate="24000/1001" in AdaptationSet.
Currently IA only supports framerate/framescale on Reprensentations.
This adds support for it on AdaptationSet as well

[proxy.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/5705549/proxy.mpd.txt)

2021-04-07 00:38 UTC, glennguy commented
Good range of tests, changes look good!

2021-04-08 10:03 UTC, phunkyfish requested changes

2021-04-08 10:03 UTC, phunkyfish commented on src/test/manifests/mpd/fps_scale_adaptset.mpd
> +</MPD>
Newline required

2021-04-08 11:29 UTC, phunkyfish approved these changes
LGTM

2021-04-08 11:41 UTC, merged