[Dash] Remove reliance on cenc: namespaces for pssh and default_kid
peak3d/inputstream.adaptive pull request #621
Opened 2021-03-25 23:56 UTC by matthuisman

- add new endswith helper function
- use endswith function to check element / attribute name ends with default_KID / pssh

This allows for mpd elements like the below (found in HBO Max)
as well as maintaining compatibility with the most common <cenc:pssh and cenc:default_KID=""

`<pssh xmlns="urn:mpeg:cenc:2013" _xmlns:cenc="urn:mpeg:cenc:2013" _xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">AAAAinBzc2gBAAAA7e+LqXnWSs6jyCfc1R0h7QAAAAMBABjPrw1FrZKp3Uaklub1AQFA6rnmTx2Vc6TOTwKt2wEC6NEQrkqOnj8BE9GY8RcAAAA2EhABABjPrw1FrZKp3Uaklub1EhABAUDqueZPHZVzpM5PAq3bEhABAujREK5Kjp4/ARPRmPEX</pssh>`

`<ContentProtection xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:_="urn:mpeg:cenc:2013" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" _:default_KID="010018CF-AF0D-45AD-92A9-DD46A496E6F5" _xmlns:cenc="urn:mpeg:cenc:2013"/>`

2021-03-26 00:05 UTC, matthuisman commented
actually, these may not be too standard...

this provider may be just doing this and using their own player.
In that case, I can just keep doing what I am now (proxy and fix)

2021-04-08 11:32 UTC, glennguy commented
> actually, these may not be too standard...

Yeah I can't find a source that doesn't mention the namespaced `cenc:pssh`, seems to be the standard for `ContentProtection` elements.
The DASH validator is not the right tool for this I think - I changed `<pssh>` to `<sshp>` and their tests still passed, so it's not checking what we're interested in.

Having said that I think what we're better off doing in these somewhat ambiguous situations is to look to what other players are doing to try and get some sort of consensus.

Exoplayer has quite wide support and if you look [here](https://github.com/google/ExoPlayer/blob/b1000940eaec9e1202d9abf341a48a58b728053f/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L582) you can see that it's ignoring whatever prefix comes with `pssh`.

Also checked DASH.js. Couldn't find any concrete code. The manifest is converted to json, and looking at the test data the namespace is stripped from the keys like this [example](https://github.com/Dash-Industry-Forum/dash.js/blob/aa033ca1f6af96af13515383b9a22d95acf0e22f/test/unit/streaming.protection.CommonEncryption.js#L11) which to me suggests that the cenc namespace isn't essential.

Maybe some runtime tests with either of these players could confirm?

2021-04-11 23:05 UTC, matthuisman commented
looks like Explayer also ignored namespace for default_kid:
https://github.com/google/ExoPlayer/blob/master/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L554

2021-04-19 00:46 UTC, matthuisman commented
@glennguy 
did you see my last comment?
Looks like bitmovin player supports <pssh as well as Exoplayer

This also has good tests so if your ok with it - can we merge it in?

2021-04-19 04:25 UTC, glennguy requested changes

2021-04-19 04:25 UTC, glennguy commented on src/helpers.cpp
> +int endswith(const char* in, const char* prefix)
Should this be 'suffix' not 'prefix'?

2021-04-19 04:38 UTC, matthuisman commented on src/helpers.cpp
> +int endswith(const char* in, const char* prefix)
oh, haha, yes!

2021-04-19 05:29 UTC, matthuisman commented
Oh. I need to rebase

2021-04-19 20:51 UTC, matthuisman commented
@glennguy  rebased and good to go :)

2021-04-20 06:04 UTC, glennguy commented
LGTM

2021-04-20 06:04 UTC, glennguy approved these changes

2021-04-20 06:07 UTC, merged