[Dash] Correctly set timeshift_buffer (live)
peak3d/inputstream.adaptive pull request #626
Opened 2021-03-31 02:28 UTC by matthuisman

With the below MPD, currently IA will set the stream to VOD when it is LIVE

This is because "mediaPresentationDuration" comes after "type".
mediaPresentationDuration sets bStatic to true

So, currently it goes
1) "type"="dynamic" which makes bStatic = false
2) "mediaPresentationDuration" which sets bStatic = true
3) dash->has_timeshift_buffer_ is set to NOT bStatic = false
4) IA think it's VOD

The order or attributes should be irrelevant.

With this PR, VOD is default and it's ever only setting LIVE to true when either dynamic or timeShiftBufferDepth found
It doesn't unset LIVE.
```
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:dvb="urn:dvb:dash:dash-extensions:2014-1" xmlns:move="http://www.movenetworks.com/dash/v1" xmlns:ms="urn:microsoft" xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" maxSegmentDuration="PT2.048000S" minBufferTime="PT2.048000S" publishTime="2020-12-07T20:30:00Z" type="dynamic" minimumUpdatePeriod="PT2.048000S" availabilityStartTime="2020-12-07T20:30:15Z" mediaPresentationDuration="PT9000.000000S" suggestedPresentationDelay="PT4.096000S">
    <ProgramInformation>
```

2021-04-01 11:24 UTC, Fireblade89 commented
I've been waiting for this for a long time. I can't wait to test it !

2021-04-01 12:57 UTC, glennguy commented
Looks good. `mediaPresentationDuration` doesn't imply VOD at all, it can be in either VOD or live. The guidelines are slightly ambiguous on this (mentions MPD 'may' be present in the context of static playlists, however doesn't explicitly mention them under dynamic playlist heading) which may have lead to the current interpretation

2021-04-01 18:24 UTC, matthuisman commented
That's what I read as well. timeShiftBufferDepth is only present with dynamic (live) so is a good identifier as well. 

We could also check profiles for is-off-live. But profiles can list multiple profiles. And I couldn't see a c++ function to search within a string. We would need to convert to std:string then find on that. Maybe something we can do in the future if we find live manifests not using type and not using timeshiftbuffer

2021-04-03 19:01 UTC, matthuisman commented
Fixes sling:
https://github.com/d21spike/plugin.video.sling/issues/22#issuecomment-812855081

2021-04-08 10:03 UTC, phunkyfish requested changes

2021-04-08 10:03 UTC, phunkyfish commented on src/test/TestDASHTree.cpp
> +}
New line required

2021-04-08 10:23 UTC, matthuisman commented
@phunkyfish  conflict fixed. New line added and also added a 2nd test

2021-04-08 11:14 UTC, phunkyfish approved these changes
LGTM

2021-04-08 11:14 UTC, merged